all:
  hosts:
    node1:
      ansible_host: ${EXT_IP}
      ip: ${INT_IP}
      access_ip: ${EXT_IP}
  children:
    kube_control_plane:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube_control_plane:
        kube-node:
    calico-rr:
      hosts: {}

